version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mynode_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mynode_db
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: